export const ADD_STUDENTS = "ADD_STUDENTS";
export const ADD_SUPERVISOR = "ADD_SUPERVISOR";
export const ADD_PROJECT = "ADD_PROJECT";

export const ALLOCATIONS = "ALLOCATIONS";
export const ALLOCATION_REQUIREMENT_REQUEST = "ALLOCATION_REQUIREMENT_REQUEST";
export const ALLOCATION_REQUIREMENT_SUCCESS = "ALLOCATION_REQUIREMENT_SUCCESS";
export const ALLOCATION_REQUIREMENT_FAILURE = "ALLOCATION_REQUIREMENT_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const DASHBOARD_COUNT = "DASHBOARD_COUNT";

export const TOKEN_REFRESH_REQUEST = "TOKEN_REFRESH_REQUEST";
export const TOKEN_REFRESH_SUCCESS = "TOKEN_REFRESH_SUCCESS";
export const TOKEN_REFRESH_FAILURE = "TOKEN_REFRESH_FAILURE";

export const USERS_REQUEST = "USERS_REQUEST";
export const USERS_SUCCESS = "USERS_SUCCESS";
export const USERS_FAILURE = "USERS_FAILURE";

export const SUPERVISORS_REQUEST = "SUPERVISORS_REQUEST";
export const SUPERVISORS_SUCCESS = "SUPERVISORS_SUCCESS";
export const SUPERVISORS_FAILURE = "SUPERVISORS_FAILURE";

export const ARCHIVES_REQUEST = "ARCHIVES_REQUEST";
export const ARCHIVES_SUCCESS = "ARCHIVES_SUCCESS";
export const ARCHIVES_FAILURE = "ARCHIVES_FAILURE";

export const ALLOCATED_REQUEST = "ALLOCATED_REQUEST";
export const ALLOCATED_SUCCESS = "ALLOCATED_SUCCESS";
export const ALLOCATED_FAILURE = "ALLOCATED_FAILURE";

export const PROGRESS_REQUEST = "PROGRESS_REQUEST";
export const PROGRESS_SUCCESS = "PROGRESS_SUCCESS";
export const PROGRESS_FAILURE = "PROGRESS_FAILURE";

export const PROJECT_REQUEST = "PROJECT_REQUEST";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_FAILURE = "PROJECT_FAILURE";

export const FETCH_ALLOCATION_REQUEST = "FETCH_ALLOCATION_REQUEST";
export const FETCH_ALLOCATION_SUCCESS = "FETCH_ALLOCATION_SUCCESS";
export const FETCH_ALLOCATION_FAILURE = "FETCH_ALLOCATION_FAILURE";

export const ADD_REQUEST = "ADD_REQUEST";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const ADD_FAILURE = "ADD_FAILURE";

export const EDIT_REQUEST = "EDIT_REQUEST";
export const EDIT_SUCCESS = "EDIT_SUCCESS";
export const EDIT_FAILURE = "EDIT_FAILURE";

export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILURE = "DELETE_FAILURE";

export const FETCH_ARCHIVES = "FETCH_ARCHIVES";
export const NEW_ALLOCATION = "NEW_ALLOCATION";
export const NEW_ALLOCATION_ERROR = "NEW_ALLOCATION_ERROR";
export const PROJECT_MESSAGE = "PROJECT_MESSAGE";

export const PROJECT_ERROR = "PROJECT_ERROR";
export const STUDENT_ERROR = "STUDENT_ERROR";
export const SUPERVISOR_ERROR = "SUPERVISOR_ERROR";

export const DELETE_USER = "DELETE_USER";
export const NEW_USER_FAILURE = "NEW_USER_FAILURE";
export const STATUS = "STATUS";
export const SET_ROLE = "SET_ROLE";
export const SUPERVISOR_STATUS = "SUPERVISOR_STATUS";

export const SET_DATA = "SET_DATA";
export const FETCHING_FAILED = "FETCHING_FAILED";
export const SET_STUDENTS_TABLE = "SET_STUDENTS_TABLE";
export const SET_SUPERVISOR_TABLE = "SET_SUPERVISOR_TABLE";

export const FETCH_PROGRESS = "FETCH_PROGRESS";
export const PROGRESS_ERROR = "PROGRESS_ERROR";
export const EDIT_PROGRESS = "EDIT_PROGRESS";
export const ADD_PROGRESS = "ADD_PROGRESS";
export const SET_MY_DATA = "SET_MY_DATA";

export const GET_USER = "GET_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const EDIT_STUDENT_TABLE = "EDIT_STUDENT_TABLE";
export const EDIT_SUPERVISOR_TABLE = "EDIT_SUPERVISOR_TABLE";
export const EDIT_PROJECT_TABLE = "EDIT_PROJECT_TABLE";

export const ALLOCATION_ERROR = "ALLOCATION_ERROR";
export const PROJECT_EDIT_ERROR = "PROJECT_EDIT_ERROR";
export const STUDENT_TABLE_ERROR = "STUDENT_TABLE_ERROR";
export const SUPERVISOR_TABLE_ERROR = "SUPERVISOR_TABLE_ERROR";

export const EDIT_ALLOCATION_TABLE = "EDIT_ALLOCATION_TABLE";
export const DELETE_ALLOCATION = "DELETE_ALLOCATION";
export const DELETE_STUDENT = "DELETE_ALLOCATION";
export const DELETE_SUPERVISOR = "DELETE_ALLOCATION";

export const DELETE_ERROR = "DELETE_ERROR";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const FETCH_PROJECTS = "FETCH_PROJECTS";
///
export const MARK_AS_COMPLETED = "MARK_AS_COMPLETED";
export const COMPLETE_ERROR = "COMPLETE_ERROR";

export const STORE_TOKEN = "STORE_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const PROFILE_STATUS = "PROFILE_STATUS";

export const STATUS_ERROR = "STATUS_ERROR";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";

export const COUNT_REQUEST = "COUNT_REQUEST";
export const COUNT_SUCCESS = "COUNT_SUCCESS";
export const COUNT_FAILURE = "COUNT_FAILURE";

export const SET_STATUS = "SET_STATUS";
export const CHANGE_ADMIN_PASSWORD = "CHANGE_ADMIN_PASSWORD";
export const CHANGE_SUPERVISOR_PASSWORD = "CHANGE_SUPERVISOR_PASSWORD";
export const ADMIN_PASS_ERROR = "ADMIN_PASS_ERROR";
export const SUPERVISOR_PASS_ERROR = "SUPERVISOR_PASS_ERROR";
