export const ADD_STUDENTS = "ADD_STUDENTS";
export const ADD_SUPERVISOR = "ADD_SUPERVISOR";
export const ADD_PROJECT = "ADD_PROJECT";

export const FETCH_ALLOCATION_STUDENTS = "FETCH_ALLOCATION_STUDENTS";
export const FETCH_ALLOCATION_LECTURERS = "FETCH_ALLOCATION_LECTURERS";

export const NEW_ALLOCATION = "NEW_ALLOCATION";
export const NEW_ALLOCATION_ERROR = "NEW_ALLOCATION_ERROR";

export const PROJECT_ERROR = "PROJECT_ERROR";
export const STUDENT_ERROR = "STUDENT_ERROR";
export const SUPERVISOR_ERROR = "SUPERVISOR_ERROR";

export const NEW_USER = "NEW_USER";
export const DELETE_USER = "DELETE_USER";
export const NEW_USER_FAILURE = "NEW_USER_FAILURE";
export const STATUS = "STATUS";
export const SET_ROLE = "SET_ROLE";

export const SET_DATA = "SET_DATA";
export const FETCHING_FAILED = "FETCHING_FAILED";
export const SET_STUDENTS_TABLE = "SET_STUDENTS_TABLE";
export const SET_SUPERVISOR_TABLE = "SET_SUPERVISOR_TABLE";

export const PROGRESS_ERROR = "PROGRESS_ERROR";
export const EDIT_PROGRESS = "EDIT_PROGRESS";
export const SET_MY_DATA = "SET_MY_DATA";

export const GET_USER = "GET_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const EDIT_STUDENT_TABLE = "EDIT_STUDENT_TABLE";
export const EDIT_SUPERVISOR_TABLE = "EDIT_SUPERVISOR_TABLE";

export const ALLOCATION_ERROR = "ALLOCATION_ERROR";
export const STUDENT_TABLE_ERROR = "STUDENT_TABLE_ERROR";
export const SUPERVISOR_TABLE_ERROR = "SUPERVISOR_TABLE_ERROR";

export const EDIT_ALLOCATION_TABLE = "EDIT_ALLOCATION_TABLE";
export const DELETE_ALLOCATION = "DELETE_ALLOCATION";
export const DELETE_STUDENT = "DELETE_ALLOCATION";
export const DELETE_SUPERVISOR = "DELETE_ALLOCATION";

export const DELETE_ERROR = "DELETE_ERROR";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const LOGOUT = "LOGOUT";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
///
export const MARK_AS_COMPLETED = "MARK_AS_COMPLETED";

export const STORE_TOKEN = "STORE_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";

export const STUDENT_COUNT = "STUDENT_COUNT";
export const SUPERVISOR_COUNT = "SUPERVISOR_COUNT";
export const DIPLOMA_STUDENTS = "DIPLOMA_STUDENTS";
export const DEGREE_STUDENTS = "DEGREE_STUDENTS";

export const SET_STATUS = "SET_STATUS";
export const CHANGE_ADMIN_PASSWORD = "CHANGE_ADMIN_PASSWORD";
export const CHANGE_SUPERVISOR_PASSWORD = "CHANGE_SUPERVISOR_PASSWORD";
export const ADMIN_PASS_ERROR = "ADMIN_PASS_ERROR";
export const SUPERVISOR_PASS_ERROR = "SUPERVISOR_PASS_ERROR";
